sudo: false

language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - pytest --verbose --cov=remedian

after_success:
- bash <(curl -s https://codecov.io/bash)
