sudo: false

language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest test/ -v --cov=./

after_success:
- codecov --token=06e24771-1394-46f3-8434-67c539e56027
