sudo: false

language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest pytest-cov

script:
  - pytest --verbose --cov=remedian

after_success:
- bash <(curl -s https://codecov.io/bash)
