sudo: false

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - pytest --verbose --cov=remedian
  - flake8 .
  - pydocstyle remedian
  - cd docs/ && make clean && make html

after_success:
- bash <(curl -s https://codecov.io/bash)
